/*
 * ZZZ-OS Buddy external-fragmentation stress test.
 * Generated by OpenAI Codex. The test is memory-only and releases every page.
 */

#include <mm/buddy.h>
#include <mm/physmem.h>
#include <os/errno.h>
#include <os/init.h>
#include <os/pfn.h>
#include <os/printk.h>
#include <os/timekeeping.h>
#include <os/types.h>

#define FRAG_MAX_BASE_PAGES       24576U /* At most 96 MiB with 4 KiB pages. */
#define FRAG_RESERVE_PAGES        4096U  /* Keep at least 16 MiB untouched. */
#define FRAG_TARGET_ORDER         9U     /* Test 2 MiB contiguous allocations. */
#define FRAG_MIN_STRESS_PAGES     4096U

static u64 fragmentation_free_pages(
    const struct buddy_fragmentation_stats *stats)
{
    return stats->buddy_free_pages + stats->pcp_free_pages;
}

/* Return hundredths of one percent, so 6750 means 67.50%. */
static u64 fragmentation_basis_points(
    const struct buddy_fragmentation_stats *stats, unsigned int target_order)
{
    u64 unusable_pages = stats->pcp_free_pages;
    u64 free_pages = fragmentation_free_pages(stats);

    if (free_pages == 0)
        return 0;

    for (u32 order = 0; order < target_order && order < MAX_ORDER; order++)
        unusable_pages += stats->free_blocks[order] << order;

    return unusable_pages * 10000ULL / free_pages;
}

static void fragmentation_report(
    const char *phase, const struct buddy_fragmentation_stats *stats)
{
    u64 free_pages = fragmentation_free_pages(stats);
    u64 frag_bp = fragmentation_basis_points(stats, FRAG_TARGET_ORDER);

    printk("fragmentation-test: phase=%s free_pages=%lu free_MiB=%lu "
           "largest_order=%d target_order=%u fragmentation_bp=%lu\n",
           phase, (unsigned long)free_pages,
           (unsigned long)(free_pages * PAGE_SIZE / (1024U * 1024U)),
           stats->largest_free_order, FRAG_TARGET_ORDER,
           (unsigned long)frag_bp);
    printk("fragmentation-orders: phase=%s o0=%lu o1=%lu o2=%lu o3=%lu "
           "o4=%lu o5=%lu o6=%lu o7=%lu o8=%lu o9=%lu o10=%lu pcp=%lu\n",
           phase,
           (unsigned long)stats->free_blocks[0],
           (unsigned long)stats->free_blocks[1],
           (unsigned long)stats->free_blocks[2],
           (unsigned long)stats->free_blocks[3],
           (unsigned long)stats->free_blocks[4],
           (unsigned long)stats->free_blocks[5],
           (unsigned long)stats->free_blocks[6],
           (unsigned long)stats->free_blocks[7],
           (unsigned long)stats->free_blocks[8],
           (unsigned long)stats->free_blocks[9],
           (unsigned long)stats->free_blocks[10],
           (unsigned long)stats->pcp_free_pages);
}

static void fragmentation_release_list(struct page *head)
{
    while (head) {
        struct page *next = head->next;

        free_pages(head);
        head = next;
    }
}

static int fragmentation_test_init(void)
{
    struct buddy_fragmentation_stats before;
    struct buddy_fragmentation_stats fragmented;
    struct buddy_fragmentation_stats exhausted;
    struct buddy_fragmentation_stats recovered;
    u64 before_free;
    u64 fragmented_bp;
    u64 exhausted_free;
    u64 start_ns = monotonic_ns();
    u32 allocation_target;
    u32 base_count = 0;
    u32 released_count = 0;
    u32 target_count = 0;
    struct page *base_head = NULL;
    struct page *target_head = NULL;
    int ret = 0;

    if (buddy_get_fragmentation_stats(&before) < 0)
        return -EIO;

    before_free = fragmentation_free_pages(&before);
    if (before_free <= FRAG_RESERVE_PAGES + FRAG_MIN_STRESS_PAGES) {
        printk("fragmentation-test: SKIP free_pages=%lu required_pages=%u\n",
               (unsigned long)before_free,
               FRAG_RESERVE_PAGES + FRAG_MIN_STRESS_PAGES);
        return 0;
    }

    allocation_target = (u32)(before_free * 4ULL / 5ULL);
    if (allocation_target > before_free - FRAG_RESERVE_PAGES)
        allocation_target = (u32)(before_free - FRAG_RESERVE_PAGES);
    if (allocation_target > FRAG_MAX_BASE_PAGES)
        allocation_target = FRAG_MAX_BASE_PAGES;

    printk("fragmentation-test: START target_order=%u target_block_MiB=%u "
           "base_target_pages=%u base_target_MiB=%lu\n",
           FRAG_TARGET_ORDER,
           (PAGE_SIZE << FRAG_TARGET_ORDER) / (1024U * 1024U),
           allocation_target,
           (unsigned long)((u64)allocation_target * PAGE_SIZE /
                           (1024U * 1024U)));
    fragmentation_report("before", &before);

    for (; base_count < allocation_target; base_count++) {
        struct page *page = alloc_pages(0);
        u8 *address;

        if (!page)
            break;
        page->next = base_head;
        base_head = page;
        address = page_address(page);
        address[0] = (u8)base_count;
        address[PAGE_SIZE - 1] = (u8)(base_count >> 8);
    }

    if (base_count < FRAG_MIN_STRESS_PAGES) {
        ret = -ENOMEM;
        goto out_release;
    }

    /*
     * Retain odd PFNs and free even PFNs. Each freed order-0 page therefore
     * has its buddy retained, preventing immediate coalescing.
     */
    {
        struct page *page = base_head;
        struct page *retained_head = NULL;

        while (page) {
            struct page *next = page->next;

            if ((page_to_pfn(page) & 1U) == 0) {
                free_pages(page);
                released_count++;
            } else {
                page->next = retained_head;
                retained_head = page;
            }
            page = next;
        }
        base_head = retained_head;
    }

    if (buddy_get_fragmentation_stats(&fragmented) < 0) {
        ret = -EIO;
        goto out_release;
    }
    fragmentation_report("fragmented", &fragmented);
    fragmented_bp = fragmentation_basis_points(&fragmented,
                                                FRAG_TARGET_ORDER);

    /* Consume every still-available target block, then observe stranded RAM. */
    while (1) {
        struct page *page = alloc_pages(FRAG_TARGET_ORDER);

        if (!page)
            break;
        page->next = target_head;
        target_head = page;
        target_count++;
    }

    if (buddy_get_fragmentation_stats(&exhausted) < 0) {
        ret = -EIO;
        goto out_release;
    }
    fragmentation_report("large_block_exhausted", &exhausted);
    exhausted_free = fragmentation_free_pages(&exhausted);

    if (base_count != allocation_target) {
        printk("fragmentation-test: FAIL short_allocation wanted=%u got=%u\n",
               allocation_target, base_count);
        ret = -ENOMEM;
    } else if (released_count == 0 || target_count == 0) {
        printk("fragmentation-test: FAIL insufficient_pressure released=%u "
               "large_blocks=%u\n", released_count, target_count);
        ret = -EIO;
    } else if (fragmented_bp < 5000ULL) {
        printk("fragmentation-test: FAIL weak_fragmentation_bp=%lu\n",
               (unsigned long)fragmented_bp);
        ret = -EIO;
    } else if (exhausted_free < (1U << FRAG_TARGET_ORDER)) {
        printk("fragmentation-test: FAIL no_stranded_free_pages=%lu\n",
               (unsigned long)exhausted_free);
        ret = -EIO;
    }

out_release:
    fragmentation_release_list(target_head);
    fragmentation_release_list(base_head);
    if (buddy_get_fragmentation_stats(&recovered) < 0)
        return -EIO;
    fragmentation_report("recovered", &recovered);

    if (fragmentation_free_pages(&recovered) != before_free) {
        printk("fragmentation-test: FAIL recovery before_pages=%lu "
               "after_pages=%lu\n", (unsigned long)before_free,
               (unsigned long)fragmentation_free_pages(&recovered));
        return -EIO;
    }
    if (ret < 0)
        return ret;

    printk("fragmentation-test: PASS allocated_pages=%u released_holes=%u "
           "large_blocks=%u stranded_pages=%lu peak_fragmentation_bp=%lu "
           "time_ms=%lu\n",
           base_count, released_count, target_count,
           (unsigned long)exhausted_free, (unsigned long)fragmented_bp,
           (unsigned long)((monotonic_ns() - start_ns) / 1000000ULL));
    return 0;
}

late_initcall(fragmentation_test_init);
