/* Generated by OpenAI Codex: read-only readahead checks and paired benchmark. */
#include <fs/file.h>
#include <fs/pagecache.h>
#include <os/err.h>
#include <os/errno.h>
#include <os/init.h>
#include <os/kmalloc.h>
#include <os/printk.h>
#include <os/string.h>
#include <os/timekeeping.h>

#define RA_TEST_PATH "/bin/ls"
#define RA_TEST_ROUNDS 3U
#define RA_TEST_BUFFER (64U * 1024U)

static bool ra_inject_error;

static int ra_mock_readpage(struct page *page)
{
    memset(pagecache_data(page), page->index & 255, PAGE_SIZE);
    return 0;
}

static int ra_mock_readpages(struct page **pages, u32 nr_pages)
{
    for (u32 i = 0; i < nr_pages; i++)
        ra_mock_readpage(pages[i]);
    return ra_inject_error ? -EIO : 0;
}

static int ra_cache_checks(void)
{
    const struct address_space_operations ops = {
        .readpage = ra_mock_readpage,
        .readpages = ra_mock_readpages,
    };
    struct inode inode = {.i_size = 600 * PAGE_SIZE + 17};
    struct address_space mapping = {.host = &inode, .a_ops = &ops};
    struct file file = {.f_inode = &inode};
    struct page *page;
    int ret;

    inode.i_mapping = &mapping;
    spin_lock_init(&mapping.lock);
    ra_inject_error = true;
    ret = pagecache_read_page(&mapping, 0, true, &page);
    if (ret < 0)
        goto out;
    ret = PageUptodate(page) && ((u8 *)pagecache_data(page))[0] == 0 ? 0 : -EIO;
    pagecache_put_page(page);
    if (ret)
        goto out;
    page = pagecache_get_page(&mapping, 1, 0);
    if (IS_ERR(page) || !page) {
        ret = -EIO;
        goto out;
    }
    ret = PageUptodate(page) ? -EIO : 0;
    pagecache_put_page(page);
    if (ret)
        goto out;
    ra_inject_error = false;
    memset(&file.f_ra, 0, sizeof(file.f_ra));
    for (u32 index = 0; index <= 600; index++) {
        ret = pagecache_read_page(&mapping, index, true, &page);
        if (ret < 0)
            goto out;
        for (u32 offset = 0; offset < PAGE_SIZE; offset++) {
            if (((u8 *)pagecache_data(page))[offset] != (index & 255)) {
                ret = -EIO;
                break;
            }
        }
        pagecache_put_page(page);
        if (ret)
            goto out;
    }
out:
    ra_inject_error = false;
    pagecache_invalidate_mapping(&mapping);
    return ret;
}

static void ra_reset(struct file *file, bool disabled)
{
    memset(&file->f_ra, 0, sizeof(file->f_ra));
    file->f_ra.disabled = disabled;
}

static int ra_pass(struct file *file, char *buffer, size_t request,
                   bool disabled, u64 *elapsed, u64 *checksum)
{
    loff_t pos = 0;
    u64 start, hash = 1469598103934665603ULL;
    int ret = pagecache_invalidate_mapping(file->f_inode->i_mapping);

    if (ret < 0)
        return ret;
    ra_reset(file, disabled);
    start = monotonic_ns();
    for (;;) {
        ssize_t count = kernel_read_at(file, pos, buffer, request);
        if (count < 0)
            return count;
        if (!count)
            break;
        for (ssize_t i = 0; i < count; i++) {
            hash ^= (u8)buffer[i];
            hash *= 1099511628211ULL;
        }
        pos += count;
    }
    *elapsed = monotonic_ns() - start;
    *checksum = hash;
    return pos == file->f_inode->i_size ? 0 : -EIO;
}

static int ra_boundaries(struct file *file, char *buffer)
{
    struct address_space *mapping = file->f_inode->i_mapping;
    struct page *page;
    char baseline[32];
    loff_t size = file->f_inode->i_size;
    ssize_t count;
    int ret;

    if (size < 32 * PAGE_SIZE)
        return -EINVAL;
    pagecache_invalidate_mapping(mapping);
    ra_reset(file, false);
    count = kernel_read_at(file, 0, buffer, PAGE_SIZE);
    if (count != PAGE_SIZE || mapping->nrpages != 1)
        return -EIO;
    count = kernel_read_at(file, PAGE_SIZE, buffer, 1);
    if (count != 1 || mapping->nrpages != 5)
        return -EIO;
    for (u32 i = 0; i < 5; i++) {
        page = pagecache_get_page(mapping, i, 0);
        if (IS_ERR(page) || !page)
            return -EIO;
        ret = PageUptodate(page) ? 0 : -EIO;
        pagecache_put_page(page);
        if (ret)
            return ret;
    }
    count = kernel_read_at(file, 20 * PAGE_SIZE, buffer, 1);
    if (count != 1 || mapping->nrpages != 6)
        return -EIO;

    ra_reset(file, true);
    count = kernel_read_at(file, size - sizeof(baseline), baseline,
                           sizeof(baseline));
    if (count != sizeof(baseline))
        return -EIO;
    pagecache_invalidate_mapping(mapping);
    ra_reset(file, false);
    memset(buffer, 0xa5, RA_TEST_BUFFER);
    count = kernel_read_at(file, size - sizeof(baseline), buffer, RA_TEST_BUFFER);
    if (count != sizeof(baseline) || memcmp(buffer, baseline, sizeof(baseline)))
        return -EIO;
    for (u32 i = sizeof(baseline); i < RA_TEST_BUFFER; i++) {
        if ((u8)buffer[i] != 0xa5)
            return -EIO;
    }
    if (kernel_read_at(file, size, buffer, 1) != 0 ||
        kernel_read_at(file, size + PAGE_SIZE, buffer, 1) != 0 ||
        kernel_read_at(file, 0, buffer, 0) != 0)
        return -EIO;
    return 0;
}

static int readahead_test_init(void)
{
    const size_t requests[] = {512, 4096, 65536};
    struct file *file = filp_open(RA_TEST_PATH, O_RDONLY);
    char *buffer;
    u64 baseline, elapsed, hash;
    int ret;

    if (IS_ERR(file))
        return PTR_ERR(file);
    buffer = page_alloc(RA_TEST_BUFFER / PAGE_SIZE);
    if (!buffer) {
        filp_close(file);
        return -ENOMEM;
    }
    ret = ra_cache_checks();
    if (ret < 0)
        goto out;
    ret = ra_boundaries(file, buffer);
    if (ret < 0)
        goto out;
    /* Warm host storage and indirect metadata; each pass drops file data. */
    ret = ra_pass(file, buffer, RA_TEST_BUFFER, true, &elapsed, &baseline);
    if (ret < 0)
        goto out;
    for (u32 i = 0; i < sizeof(requests) / sizeof(requests[0]); i++) {
        u64 total[2] = {0, 0};
        for (u32 round = 0; round < RA_TEST_ROUNDS; round++) {
            for (u32 order = 0; order < 2; order++) {
                u32 enabled = (round + order) & 1;
                ret = ra_pass(file, buffer, requests[i], !enabled, &elapsed, &hash);
                if (ret < 0 || hash != baseline) {
                    ret = ret < 0 ? ret : -EIO;
                    goto out;
                }
                total[enabled] += elapsed;
            }
        }
        for (u32 enabled = 0; enabled < 2; enabled++) {
            printk("readahead-test: request=%lu enabled=%u rounds=%u bytes=%lu "
                   "avg_us=%llu KiB_s=%llu checksum=%llx\n",
                   (unsigned long)requests[i], enabled, RA_TEST_ROUNDS,
                   (unsigned long)file->f_inode->i_size,
                   (unsigned long long)(total[enabled] / RA_TEST_ROUNDS / 1000),
                   (unsigned long long)((u64)file->f_inode->i_size *
                       RA_TEST_ROUNDS * NSEC_PER_SEC /
                       (total[enabled] ? total[enabled] : 1) / 1024),
                   (unsigned long long)baseline);
        }
    }
out:
    printk("readahead-test: %s ret=%d\n", ret ? "FAIL" : "PASS", ret);
    page_free(buffer);
    filp_close(file);
    return ret;
}

late_initcall(readahead_test_init);
